"""Update User and Message Table

Revision ID: b942d0f26984
Revises: 8cfdd0072fbf
Create Date: 2025-06-19 17:46:15.356075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b942d0f26984'
down_revision: Union[str, Sequence[str], None] = '8cfdd0072fbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.add_column('messages', sa.Column('read_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_messages_recipient_id'), 'messages', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_recipient_id'), table_name='messages')
    op.drop_column('messages', 'read_at')
    op.drop_column('messages', 'is_read')
    # ### end Alembic commands ###
